 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/questions", type: :request do
  # Question. As you add validations to Question, be sure to
  # adjust the attributes here as well.
  let(:exam) { FactoryBot.create(:exam) }
  let(:valid_attributes) {
    {
      prompt: "MyPrompt",
      source: "MySource",
      exam_id: exam.id
    }
  }

  let(:invalid_attributes) {
    exam = FactoryBot.create(:exam)
    {
      prompt: nil,
      source: "MySource",
      exam_id: exam.id
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Question.create! valid_attributes
      get exam_questions_url(exam)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      question = Question.create! valid_attributes
      get question_url(question)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_exam_question_url(exam)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      question = Question.create! valid_attributes
      get edit_question_url(question)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Question" do
        expect {
          post exam_questions_url(exam), params: { question: valid_attributes }
        }.to change(Question, :count).by(1)
      end

      it "redirects to the created question" do
        post exam_questions_url(exam), params: { question: valid_attributes }
        expect(response).to redirect_to(question_url(Question.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Question" do
        expect {
          post exam_questions_url(exam), params: { question: invalid_attributes }
        }.to change(Question, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post exam_questions_url(exam), params: { question: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          prompt: "NewPrompt",
          source: "NewSource",
        }
      }

      it "updates the requested question" do
        question = Question.create! valid_attributes
        patch question_url(question), params: { question: new_attributes }
        question.reload
        expect(question.prompt).to eq("NewPrompt")
        expect(question.source).to eq("NewSource")
      end

      it "redirects to the question" do
        question = Question.create! valid_attributes
        patch question_url(question), params: { question: new_attributes }
        question.reload
        expect(response).to redirect_to(question_url(question))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        question = Question.create! valid_attributes
        patch question_url(question), params: { question: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested question" do
      question = Question.create! valid_attributes
      expect {
        delete question_url(question)
      }.to change(Question, :count).by(-1)
    end

    it "redirects to the questions list" do
      question = Question.create! valid_attributes
      delete question_url(question)
      expect(response).to redirect_to(exam_questions_url(exam))
    end
  end
end
